### ISSUE TITLE
Error at new LauncherError when trying to download

### ISSUE THREAD

**Issue by RaulRohjans** [animeloyalty/animesync#30]
Im getting an error when I try to download an entire anime from crunchyroll. All app settings are default and I am logged in with the correct credentials. Im running ubuntu server 20.04 LTS from a VM.

![imagem](https://user-images.githubusercontent.com/77687494/119274486-100d4f00-bc08-11eb-86c9-4806fef0dc54.png)

**Comment by Deathspike** [comment]
This looks like an issue with missing dependencies.
Specifically, it complains that *Google Chrome* can't be found.
Can you check that you have it installed?

**Comment by RaulRohjans** [comment]
I was able to fix that issue with `sudo apt --fix-broken install` but now it gives me a credentials error. I have verified and everything is correct.

![imagem](https://user-images.githubusercontent.com/77687494/119410185-5a61ff00-bce0-11eb-85ce-54ba0cb4709f.png)

**Comment by Deathspike** [comment]
I've identified and fixed the issue in `0.11.8`. Please update and try again!

**Comment by RaulRohjans** [comment]
That solved my problem, though I had to set a custom path to ffmpeg, you should mention that might be needed in the Readme. Thank you!
