### ISSUE TITLE
Is there any way to get the get the video and subtitles in separated?

### ISSUE THREAD

**Issue by RaulRohjans** [animeloyalty/animesync#34]
As of now, when I download an episode, the video file and episode file get bunddled in a mkv file, is there any way to get a .mp4 and a .ass, .srt or .vvt instead?

**Comment by Deathspike** [comment]
There isn't anything in `animesync` for that right now.
If there's a really good use case, I'll consider adding support for it.
Why do you need to separate the files rather than using the `.mkv`?

**Comment by RaulRohjans** [comment]
Im going to use this on a web project of mine, and I want people to be able to change the subtitle track, for this I need an mp4 with no subtitles and the subtitle tracks seperate. I could have a different mkv file for each language but that would take up too much space and wouldnt be a nice solution.

**Comment by Deathspike** [comment]
Perhaps the API suffices? Try running `animesync server` and opening http://localhost:6583/api/.
You'll find that `/api/remote/stream` yields `sources` and `subtitles`.

The `sources` contains the video metadata and URL, and `subtitles` contains the subtitle formats and URL.
Then you can either directly stream the files, or download (video w/ `ffmpeg`) and organize them however you see fit.

For examples, see:
https://github.com/animeloyalty/animeloyalty
https://github.com/animeloyalty/animeloyalty-client/blob/master/src/remote/viewModels/StreamViewModel.ts#L49
https://github.com/animeloyalty/animesync/blob/master/src/cli/classes/Sync.ts#L20

**Comment by RaulRohjans** [comment]
Hopefully Ill be able to achieve what I want, thanks again.

**Comment by Deathspike** [comment]
You're welcome! Let me know if you have further questions 👍
